//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yyscamper.ProgCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yyscamper.ProgCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_fav {
            get {
                object obj = ResourceManager.GetObject("add_fav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAddToClipboard {
            get {
                object obj = ResourceManager.GetObject("imgAddToClipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAddToVarList {
            get {
                object obj = ResourceManager.GetObject("imgAddToVarList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Clipboard 的本地化字符串。
        /// </summary>
        internal static string strAddToClipboard {
            get {
                return ResourceManager.GetString("strAddToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add To Variable List 的本地化字符串。
        /// </summary>
        internal static string strAddToVarList {
            get {
                return ResourceManager.GetString("strAddToVarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The result is not valid! 的本地化字符串。
        /// </summary>
        internal static string strAddVarResultErrorMessage {
            get {
                return ResourceManager.GetString("strAddVarResultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProgCalc 的本地化字符串。
        /// </summary>
        internal static string strAppName {
            get {
                return ResourceManager.GetString("strAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyscamper 的本地化字符串。
        /// </summary>
        internal static string strAuthor {
            get {
                return ResourceManager.GetString("strAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyscamper@163.com 的本地化字符串。
        /// </summary>
        internal static string strAuthorEmail {
            get {
                return ResourceManager.GetString("strAuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 progcalc_config.xml 的本地化字符串。
        /// </summary>
        internal static string strConfigFileName {
            get {
                return ResourceManager.GetString("strConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CustomResult 的本地化字符串。
        /// </summary>
        internal static string strXmlCustomResultNodeName {
            get {
                return ResourceManager.GetString("strXmlCustomResultNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FavoriateExpression 的本地化字符串。
        /// </summary>
        internal static string strXmlFavExpNodeName {
            get {
                return ResourceManager.GetString("strXmlFavExpNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variables 的本地化字符串。
        /// </summary>
        internal static string strXmlVarNodeName {
            get {
                return ResourceManager.GetString("strXmlVarNodeName", resourceCulture);
            }
        }
    }
}
